export const folders = [
  { id: 'grade8', label: 'Grade 8', color: '#8b5cf6', count: 6 },
  { id: 'grade9', label: 'Grade 9', color: '#6366f1', count: 10 },
  { id: 'grade10', label: 'Grade 10', color: '#06b6d4', count: 3 },
  { id: 'grade11', label: 'Grade 11', color: '#f59e0b', count: 11 },
  { id: 'grade12', label: 'Grade 12', color: '#ef4444', count: 4 },
  { id: 'exam', label: 'Exam Preparation', color: '#f97316', count: 5 },
  { id: 'natural', label: 'Natural Stream', color: '#10b981', count: 5 },
  { id: 'social', label: 'Social Stream', color: '#ec4899', count: 4 },
];

export const books = [
  { title: 'Grade 8 Amharic', author: 'MoE Textbook', folderId: 'grade8', rating: 4.3, pages: 180, color: '#8b5cf6' },
  { title: 'Grade 8 Mathematics', author: 'MoE Textbook', folderId: 'grade8', rating: 4.4, pages: 240, color: '#8b5cf6' },
  { title: 'Grade 8 English', author: 'MoE Textbook', folderId: 'grade8', rating: 4.3, pages: 190, color: '#8b5cf6' },
  { title: 'Grade 8 Science', author: 'MoE Textbook', folderId: 'grade8', rating: 4.4, pages: 220, color: '#8b5cf6' },
  { title: 'Grade 8 Social Studies', author: 'MoE Textbook', folderId: 'grade8', rating: 4.2, pages: 170, color: '#8b5cf6' },
  { title: 'Grade 8 Civics', author: 'MoE Textbook', folderId: 'grade8', rating: 4.2, pages: 150, color: '#8b5cf6' },
  { title: 'Grade 9 Amharic', author: 'MoE Textbook', folderId: 'grade9', rating: 4.4, pages: 190, color: '#6366f1', cover: 'https://kehulum.com/up_asset/b/291/kehulum17000662613aa345e0e0.png', pdfUrl: 'https://kehulum.com/books_asset/books_91/collection/grade-9-amharic-new-curriculum--student-textbook-kehulumcom1759933673b3a1.pdf' },
  { title: 'Grade 9 Biology', author: 'MoE Textbook', folderId: 'grade9', rating: 4.5, pages: 280, color: '#6366f1', cover: 'https://kehulum.com/up_asset/b/292/kehulum1700066941b553ce998a.png' },
  { title: 'Grade 9 Chemistry', author: 'MoE Textbook', folderId: 'grade9', rating: 4.4, pages: 260, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/469/kehulumcom-1742642618010770c948.png' },
  { title: 'Grade 9 Civics', author: 'MoE Textbook', folderId: 'grade9', rating: 4.3, pages: 180, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/481/kehulumcom-174264782609c4da4851.png' },
  { title: 'Grade 9 English', author: 'MoE Textbook', folderId: 'grade9', rating: 4.3, pages: 200, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/470/kehulumcom-174264276534dd6d8722.png' },
  { title: 'Grade 9 History', author: 'MoE Textbook', folderId: 'grade9', rating: 4.4, pages: 220, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/473/kehulumcom-1742644271548691bc62.png' },
  { title: 'Grade 9 Geography', author: 'MoE Textbook', folderId: 'grade9', rating: 4.4, pages: 240, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/471/kehulumcom-17426429443154cfb6c7.png' },
  { title: 'Grade 9 HPE', author: 'MoE Textbook', folderId: 'grade9', rating: 4.2, pages: 160, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/474/kehulumcom-174264453050a529343e.png' },
  { title: 'Grade 9 IT', author: 'MoE Textbook', folderId: 'grade9', rating: 4.5, pages: 200, color: '#6366f1', cover: 'https://kehulum.com/ups_asset/b/475/kehulumcom-174264496625a07a0669.png' },
  { title: 'Grade 9 Economics', author: 'MoE Textbook', folderId: 'grade9', rating: 4.3, pages: 180, color: '#6366f1', cover: 'https://kehulum.com/up_asset/b/295/kehulum1700073874846cdfbb7d.png' },
  { title: 'Grade 10 Mathematics', author: 'MoE Textbook', folderId: 'grade10', rating: 4.6, pages: 320, color: '#06b6d4' },
  { title: 'Grade 10 English', author: 'MoE Textbook', folderId: 'grade10', rating: 4.4, pages: 220, color: '#06b6d4' },
  { title: 'Grade 10 Physics', author: 'MoE Textbook', folderId: 'grade10', rating: 4.5, pages: 260, color: '#06b6d4' },
  { title: 'Grade 11 Amharic', author: 'MoE Textbook', folderId: 'grade11', rating: 4.5, pages: 240, color: '#f59e0b', cover: 'https://kehulum.com/ups_asset/b/416/kehulumcom1734351344694b577e90.png' },
  { title: 'Grade 11 Agriculture', author: 'MoE Textbook', folderId: 'grade11', rating: 4.4, pages: 220, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/315/kehulum170011602717f0c093dd.png' },
  { title: 'Grade 11 Biology', author: 'MoE Textbook', folderId: 'grade11', rating: 4.8, pages: 340, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/316/kehulum1700116467aed7867497.png' },
  { title: 'Grade 11 Chemistry', author: 'MoE Textbook', folderId: 'grade11', rating: 4.5, pages: 310, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/317/kehulum170011674174ee1b2b18.png' },
  { title: 'Grade 11 Economics', author: 'MoE Textbook', folderId: 'grade11', rating: 4.6, pages: 220, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/318/kehulum1700117037365f312a63.png' },
  { title: 'Grade 11 English', author: 'MoE Textbook', folderId: 'grade11', rating: 4.6, pages: 280, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/319/kehulum17001180039aa8027c68.png' },
  { title: 'Grade 11 Geography', author: 'MoE Textbook', folderId: 'grade11', rating: 4.4, pages: 260, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/320/kehulum1700118327db25ab5de4.png' },
  { title: 'Grade 11 History', author: 'MoE Textbook', folderId: 'grade11', rating: 4.5, pages: 240, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/321/kehulum1700118616884c7ac62d.png' },
  { title: 'Grade 11 Mathematics', author: 'MoE Textbook', folderId: 'grade11', rating: 4.7, pages: 340, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/323/kehulum17001201399d965dcf62.png' },
  { title: 'Grade 11 Physics', author: 'MoE Textbook', folderId: 'grade11', rating: 4.7, pages: 280, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/324/kehulum170012144699c87dbe79.png' },
  { title: 'Grade 11 IT', author: 'MoE Textbook', folderId: 'grade11', rating: 4.5, pages: 200, color: '#f59e0b', cover: 'https://kehulum.com/up_asset/b/322/kehulum1700118913b7d858f82a.png' },
  { title: 'Grade 12 Mathematics', author: 'MoE Textbook', folderId: 'grade12', rating: 4.7, pages: 360, color: '#ef4444' },
  { title: 'Grade 12 Physics', author: 'MoE Textbook', folderId: 'grade12', rating: 4.8, pages: 300, color: '#ef4444' },
  { title: 'Grade 12 History', author: 'MoE Textbook', folderId: 'grade12', rating: 4.5, pages: 250, color: '#ef4444' },
  { title: 'Grade 12 Geography', author: 'MoE Textbook', folderId: 'grade12', rating: 4.4, pages: 230, color: '#ef4444' },
  { title: 'National Exam Math Practice', author: 'MoE Textbook', folderId: 'exam', rating: 4.7, pages: 200, color: '#f97316', cover: '/exam-prep.webp' },
  { title: 'National Exam English Practice', author: 'MoE Textbook', folderId: 'exam', rating: 4.6, pages: 180, color: '#f97316', cover: '/exam-prep.webp' },
  { title: 'National Exam Amharic Practice', author: 'MoE Textbook', folderId: 'exam', rating: 4.5, pages: 160, color: '#f97316', cover: '/exam-prep.webp' },
  { title: 'University Entrance Exam Guide', author: 'MoE Textbook', folderId: 'exam', rating: 4.8, pages: 280, color: '#f97316', cover: '/exam-prep.webp' },
  { title: 'Exam Prep Study Strategies', author: 'MoE Textbook', folderId: 'exam', rating: 4.4, pages: 120, color: '#f97316', cover: '/exam-prep.webp' },
  { title: 'Physics (Natural)', author: 'MoE Textbook', folderId: 'natural', rating: 4.8, pages: 280, color: '#10b981' },
  { title: 'Chemistry (Natural)', author: 'MoE Textbook', folderId: 'natural', rating: 4.6, pages: 310, color: '#10b981' },
  { title: 'Biology (Natural)', author: 'MoE Textbook', folderId: 'natural', rating: 4.8, pages: 340, color: '#10b981' },
  { title: 'Mathematics (Natural)', author: 'MoE Textbook', folderId: 'natural', rating: 4.7, pages: 360, color: '#10b981' },
  { title: 'ICT (Natural)', author: 'MoE Textbook', folderId: 'natural', rating: 4.5, pages: 200, color: '#10b981' },
  { title: 'History (Social)', author: 'MoE Textbook', folderId: 'social', rating: 4.5, pages: 240, color: '#ec4899' },
  { title: 'Geography (Social)', author: 'MoE Textbook', folderId: 'social', rating: 4.4, pages: 260, color: '#ec4899' },
  { title: 'Economics (Social)', author: 'MoE Textbook', folderId: 'social', rating: 4.6, pages: 220, color: '#ec4899' },
  { title: 'Civics (Social)', author: 'MoE Textbook', folderId: 'social', rating: 4.3, pages: 200, color: '#ec4899' },
];

export const grades = [
  { id: 'grade8', label: 'Grade 8', books: 6, students: '12K+', color: '#8b5cf6', image: '/grade-8.svg' },
  { id: 'grade9', label: 'Grade 9', books: 10, students: '25K+', color: '#6366f1', image: '/grade-9.svg' },
  { id: 'grade10', label: 'Grade 10', books: 3, students: '18K+', color: '#06b6d4', image: '/grade-10.svg' },
  { id: 'natural', label: 'Natural Stream', books: 5, students: '22K+', color: '#10b981', image: '/natural-stream.svg' },
  { id: 'social', label: 'Social Stream', books: 4, students: '15K+', color: '#ec4899', image: '/social-stream.svg' },
  { id: 'exam', label: 'Exam Prep', books: 5, students: '30K+', color: '#f97316', image: '/exam-prep-card.svg' },
];

export const textbooks = [
  { subject: 'Mathematics', grade: 'Grade 11', gradeId: 'grade11', downloads: '15,000', color: '#f59e0b', cover: '/popular-maths.webp' },
  { subject: 'English', grade: 'Grade 11', gradeId: 'grade11', downloads: '12,500', color: '#f59e0b', cover: '/popular-english.webp' },
  { subject: 'Physics', grade: 'Grade 11', gradeId: 'grade11', downloads: '10,200', color: '#f59e0b', cover: '/popular-physics.webp' },
  { subject: 'Chemistry', grade: 'Grade 11', gradeId: 'grade11', downloads: '9,800', color: '#f59e0b', cover: '/popular-chemistry.webp' },
];

export const folderMeta = {
  grade8: {
    description: 'Free Grade 8 Ethiopian textbooks in PDF. Download Amharic, Mathematics, English, Science, Social Studies, and Civics textbooks for the Ethiopian curriculum.',
    keywords: ['Grade 8 textbook Ethiopia', 'Grade 8 Amharic textbook', 'Grade 8 Mathematics', 'Grade 8 English', 'Grade 8 Science', 'Grade 8 Social Studies', 'Grade 8 Civics', 'Ethiopian grade 8 books', 'የ8ኛ ክፍል መጽሐፍት'],
    subjects: ['Amharic', 'Mathematics', 'English', 'Science', 'Social Studies', 'Civics'],
  },
  grade9: {
    description: 'Download free Grade 9 Ethiopian textbooks in PDF. Complete set of 10 subjects including Amharic, Biology, Chemistry, English, History, and more for the new curriculum.',
    keywords: ['Grade 9 textbook Ethiopia', 'Grade 9 Amharic PDF', 'Grade 9 Biology', 'Grade 9 Chemistry', 'Grade 9 English', 'Grade 9 History', 'Grade 9 Geography', 'Ethiopian grade 9 books', 'የ9ኛ ክፍል መጽሐፍት', 'grade 9 new curriculum'],
    subjects: ['Amharic', 'Biology', 'Chemistry', 'Civics', 'English', 'History', 'Geography', 'HPE', 'IT', 'Economics'],
  },
  grade10: {
    description: 'Free Grade 10 Ethiopian textbooks PDF download. Access Mathematics, English, and Physics textbooks for the Ethiopian secondary school curriculum.',
    keywords: ['Grade 10 textbook Ethiopia', 'Grade 10 Mathematics', 'Grade 10 English', 'Grade 10 Physics', 'Ethiopian grade 10 books', 'የ10ኛ ክፍል መጽሐፍት'],
    subjects: ['Mathematics', 'English', 'Physics'],
  },
  grade11: {
    description: 'Download 11 free Grade 11 Ethiopian textbooks in PDF. Complete set: Amharic, Agriculture, Biology, Chemistry, Economics, English, Geography, History, Mathematics, Physics, IT.',
    keywords: ['Grade 11 textbook Ethiopia', 'Grade 11 Biology', 'Grade 11 Chemistry', 'Grade 11 Mathematics', 'Grade 11 Physics', 'Grade 11 English', 'Ethiopian grade 11 books', 'የ11ኛ ክፍል መጽሐፍት', 'grade 11 natural science'],
    subjects: ['Amharic', 'Agriculture', 'Biology', 'Chemistry', 'Economics', 'English', 'Geography', 'History', 'Mathematics', 'Physics', 'IT'],
  },
  grade12: {
    description: 'Free Grade 12 Ethiopian textbooks PDF download for Mathematics, Physics, History, and Geography. Prepare for national exams with MoE-approved materials.',
    keywords: ['Grade 12 textbook Ethiopia', 'Grade 12 Mathematics', 'Grade 12 Physics', 'Grade 12 History', 'Grade 12 Geography', 'Ethiopian grade 12 books', 'የ12ኛ ክፍል መጽሐፍት', 'grade 12 exam prep'],
    subjects: ['Mathematics', 'Physics', 'History', 'Geography'],
  },
  exam: {
    description: 'Free Ethiopian National Exam preparation materials. Download practice tests, study guides, and past papers for university entrance and Grade 10 national exams.',
    keywords: ['Ethiopian national exam prep', 'Grade 12 exam preparation', 'university entrance exam Ethiopia', 'past papers Ethiopia', 'exam study guide', 'national exam practice', 'የ12ኛ ክፍል ፈተና', 'የመግቢያ ፈተና'],
    subjects: ['Mathematics', 'English', 'Amharic', 'Study Skills'],
  },
  natural: {
    description: 'Free Natural Stream textbooks PDF download for Ethiopian students. Access Physics, Chemistry, Biology, Mathematics, and ICT textbooks for grades 11-12 natural science track.',
    keywords: ['Natural stream textbook Ethiopia', 'Physics textbook Ethiopia', 'Chemistry textbook', 'Biology textbook', 'Mathematics natural stream', 'ICT textbook', 'የተፈጥሮ ሳይንስ መጽሐፍት'],
    subjects: ['Physics', 'Chemistry', 'Biology', 'Mathematics', 'ICT'],
  },
  social: {
    description: 'Free Social Stream textbooks PDF download for Ethiopian students. Access History, Geography, Economics, and Civics textbooks for the social science track.',
    keywords: ['Social stream textbook Ethiopia', 'History textbook Ethiopia', 'Geography textbook', 'Economics textbook', 'Civics textbook', 'የማህበራዊ ሳይንስ መጽሐፍት'],
    subjects: ['History', 'Geography', 'Economics', 'Civics'],
  },
};
